baseURL = "https://blog-dev-jianse.vercel.app/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
title = "Jianse's note"
copyright = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh)"
theme = "diary"
# googleAnalytics = "UA-123-45"

# enable git info to make lastMod work properly
enableGitInfo = true
hasCJKLanguage = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1

[params]
debug = true
subtitle = "1.01*365"
enableGitalk = false

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = false
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

enableBlockquoteEnhance = true
enableCodeLangTag = true
enableAutoDarkMode = true
enableMathJax = true
enableMediumZoom = true

enableReadingTime = true
openLinkInNewTab = true
enableServiceWorker = true


[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/posts/"
name = "文章"
weight = 1

[[menu.main]]
url = "/categories/"
name = "分类"
weight = 2

[[menu.main]]
url = "/tags/"
name = "标签"
weight = 3

[[menu.main]]
url = "/about/"
name = "关于"
weight = 4

[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 5

[minify]
  minifyOutput = false